<?php

namespace Database\Seeders;

use App\Models\ApiCategories;
use App\Models\ApiInfo;
use App\Models\User;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $this->apis();
        $this->category();
    }
    public function apis()
    {
        $api = [
            [
                'name' => 'Connection Test',
                'category_id' => 1,
                'endpoint' => '/api/ConnectionTest',
                'method' => 'POST',
                'description' => 'This API is used to test the connection between the Product and the Agora License Manager.',
                'parameters' => json_encode([
                    [
                        'params' => 'product_id',
                        'type' => 'Integer',
                        'opt_or_req' => 'Required',
                        'description' => 'The key of the product Id',
                        'values' => '8',
                    ],
                    [
                        'params' => 'connection_hash',
                        'type' => 'String',
                        'opt_or_req' => 'Required',
                        'description' => 'The hash of the connection',
                        'values' => rawurlencode(hash('sha256', 'connection_test')),
                    ],
                ]),
                'is_active' => 1,
            ],
            [
                'name' => 'License Install',
                'category_id' => 1,
                'endpoint' => '/api/licenseInstall',
                'method' => 'POST',
                'description' => 'This is used by script on users machine to check if license is active and add installation details to Agora License Manager database during installation of protected script',
                'parameters' => json_encode([
                    [
                        'params' => 'product_id',
                        'type' => 'Integer',
                        'opt_or_req' => 'Required',
                        'description' => 'The key of the product Id',
                        'values' => '8',
                    ],
                    [
                        'params' => 'client_email',
                        'type' => 'String',
                        'opt_or_req' => 'Optional',
                        'description' => 'The email of the client',
                        'values' => '',
                    ],
                    [
                        'params' => 'license_code',
                        'type' => 'String',
                        'opt_or_req' => 'Required',
                        'description' => 'The code of the license',
                        'values' => 'VWNKDSNCJKCNSU89',
                    ],
                    [
                        'params' => 'root_url',
                        'type' => 'String',
                        'opt_or_req' => 'Required',
                        'description' => 'The domain URL of the product',
                        'values' => 'https://demo.localhost/',
                    ],
                    [
                        'params' => 'installation_hash',
                        'type' => 'String',
                        'opt_or_req' => 'Required',
                        'description' => 'The random hash of the installation',
                        'values' => '75hgvdhgwvkjgweyu2t675672f3kjgb3gbrhg',
                    ],
                    [
                        'params' => 'license_signature',
                        'type' => 'String',
                        'opt_or_req' => 'Required',
                        'description' => 'The random hash of the license',
                        'values' => 'uyyf3ytfgvq23ehq3y3tq362t763e2873y81723',
                    ]
                ]),
                'is_active' => 1,
            ],
            [
                'name' => 'License Scheme',
                'category_id' => 1,
                'endpoint' => '/api/licenseScheme',
                'method' => 'POST',
                'description' => 'This is used by script on users machine to check if license is active and get MySQL scheme for local license storage from Agora License Manager database during installation of protected script',
                'parameters' => json_encode([
                    [
                        'params' => 'product_id',
                        'type' => 'Integer',
                        'opt_or_req' => 'Required',
                        'description' => 'The key of the product Id',
                        'values' => '8',
                    ],
                    [
                        'params' => 'client_email',
                        'type' => 'String',
                        'opt_or_req' => 'Optional',
                        'description' => 'The email of the client',
                        'values' => '',
                    ],
                    [
                        'params' => 'license_code',
                        'type' => 'String',
                        'opt_or_req' => 'Required',
                        'description' => 'The code of the license',
                        'values' => 'VWNKDSNCJKCNSU89',
                    ],
                    [
                        'params' => 'root_url',
                        'type' => 'String',
                        'opt_or_req' => 'Required',
                        'description' => 'The domain URL of the product',
                        'values' => 'https://demo.localhost/',
                    ],
                    [
                        'params' => 'installation_hash',
                        'type' => 'String',
                        'opt_or_req' => 'Required',
                        'description' => 'The random hash of the installation',
                        'values' => '75hgvdhgwvkjgweyu2t675672f3kjgb3gbrhg',
                    ],
                    [
                        'params' => 'license_signature',
                        'type' => 'String',
                        'opt_or_req' => 'Required',
                        'description' => 'The random hash of the license',
                        'values' => 'uyyf3ytfgvq23ehq3y3tq362t763e2873y81723',
                    ]
                ]),
                'is_active' => 1,
            ],
            [
                'name' => 'License Verify',
                'category_id' => 1,
                'endpoint' => '/api/licenseVerify',
                'method' => 'POST',
                'description' => 'This is used by script on users machine to check if license is active and add callback details to Agora License Manager database during license check of protected script',
                'parameters' => json_encode([
                    [
                        'params' => 'product_id',
                        'type' => 'Integer',
                        'opt_or_req' => 'Required',
                        'description' => 'The key of the product Id',
                        'values' => '8',
                    ],
                    [
                        'params' => 'client_email',
                        'type' => 'String',
                        'opt_or_req' => 'Optional',
                        'description' => 'The email of the client',
                        'values' => '',
                    ],
                    [
                        'params' => 'license_code',
                        'type' => 'String',
                        'opt_or_req' => 'Required',
                        'description' => 'The code of the license',
                        'values' => 'VWNKDSNCJKCNSU89',
                    ],
                    [
                        'params' => 'root_url',
                        'type' => 'String',
                        'opt_or_req' => 'Required',
                        'description' => 'The domain URL of the product',
                        'values' => 'https://demo.localhost/',
                    ],
                    [
                        'params' => 'installation_hash',
                        'type' => 'String',
                        'opt_or_req' => 'Required',
                        'description' => 'The random hash of the installation',
                        'values' => '75hgvdhgwvkjgweyu2t675672f3kjgb3gbrhg',
                    ],
                    [
                        'params' => 'license_signature',
                        'type' => 'String',
                        'opt_or_req' => 'Required',
                        'description' => 'The random hash of the license',
                        'values' => 'uyyf3ytfgvq23ehq3y3tq362t763e2873y81723',
                    ]
                ]),
                'is_active' => 1,
            ],
            [
                'name' => 'Specific Version Details',
                'category_id' => 1,
                'endpoint' => '/api/getVersions',
                'method' => 'POST',
                'description' => 'This API is used to get the specific version details.',
                'parameters' => json_encode([
                    [
                        'params' => 'product_id',
                        'type' => 'Integer',
                        'opt_or_req' => 'Required',
                        'description' => 'The key of the product Id',
                        'values' => '8',
                    ],
                    [
                        'params' => 'client_email',
                        'type' => 'String',
                        'opt_or_req' => 'Optional',
                        'description' => 'The email of the client',
                        'values' => '',
                    ],
                    [
                        'params' => 'license_code',
                        'type' => 'String',
                        'opt_or_req' => 'Required',
                        'description' => 'The code of the license',
                        'values' => 'VWNKDSNCJKCNSU89',
                    ],
                    [
                        'params' => 'root_url',
                        'type' => 'String',
                        'opt_or_req' => 'Required',
                        'description' => 'The domain URL of the product',
                        'values' => 'https://demo.localhost/',
                    ],
                    [
                        'params' => 'installation_hash',
                        'type' => 'String',
                        'opt_or_req' => 'Required',
                        'description' => 'The random hash of the installation',
                        'values' => '75hgvdhgwvkjgweyu2t675672f3kjgb3gbrhg',
                    ],
                    [
                        'params' => 'license_signature',
                        'type' => 'String',
                        'opt_or_req' => 'Required',
                        'description' => 'The random hash of the license',
                        'values' => 'uyyf3ytfgvq23ehq3y3tq362t763e2873y81723',
                    ]
                ]),
                'is_active' => 1,
            ],
            [
                'name' => 'Get All Versions Details',
                'category_id' => 1,
                'endpoint' => '/api/getAllVersions',
                'method' => 'POST',
                'description' => 'This API is used to get all version details.',
                'parameters' => json_encode([
                    [
                        'params' => 'product_id',
                        'type' => 'Integer',
                        'opt_or_req' => 'Required',
                        'description' => 'The key of the product Id',
                        'values' => '8',
                    ],
                    [
                        'params' => 'client_email',
                        'type' => 'String',
                        'opt_or_req' => 'Optional',
                        'description' => 'The email of the client',
                        'values' => '',
                    ],
                    [
                        'params' => 'license_code',
                        'type' => 'String',
                        'opt_or_req' => 'Required',
                        'description' => 'The code of the license',
                        'values' => 'VWNKDSNCJKCNSU89',
                    ],
                    [
                        'params' => 'root_url',
                        'type' => 'String',
                        'opt_or_req' => 'Required',
                        'description' => 'The domain URL of the product',
                        'values' => 'https://demo.localhost/',
                    ],
                    [
                        'params' => 'installation_hash',
                        'type' => 'String',
                        'opt_or_req' => 'Required',
                        'description' => 'The random hash of the installation',
                        'values' => '75hgvdhgwvkjgweyu2t675672f3kjgb3gbrhg',
                    ],
                    [
                        'params' => 'license_signature',
                        'type' => 'String',
                        'opt_or_req' => 'Required',
                        'description' => 'The random hash of the license',
                        'values' => 'uyyf3ytfgvq23ehq3y3tq362t763e2873y81723',
                    ]
                ]),
                'is_active' => 1,
            ],
            [
                'name' => 'Fetch Query of Specific Version',
                'category_id' => 1,
                'endpoint' => '/api/fetchQuery',
                'method' => 'POST',
                'description' => 'This API is used to fetch MySQL query of a specified version.',
                'parameters' => json_encode([
                    [
                        'params' => 'product_id',
                        'type' => 'Integer',
                        'opt_or_req' => 'Required',
                        'description' => 'The key of the product Id',
                        'values' => '8',
                    ],
                    [
                        'params' => 'client_email',
                        'type' => 'String',
                        'opt_or_req' => 'Optional',
                        'description' => 'The email of the client',
                        'values' => '',
                    ],
                    [
                        'params' => 'license_code',
                        'type' => 'String',
                        'opt_or_req' => 'Required',
                        'description' => 'The code of the license',
                        'values' => 'VWNKDSNCJKCNSU89',
                    ],
                    [
                        'params' => 'root_url',
                        'type' => 'String',
                        'opt_or_req' => 'Required',
                        'description' => 'The domain URL of the product',
                        'values' => 'https://demo.localhost/',
                    ],
                    [
                        'params' => 'installation_hash',
                        'type' => 'String',
                        'opt_or_req' => 'Required',
                        'description' => 'The random hash of the installation',
                        'values' => '75hgvdhgwvkjgweyu2t675672f3kjgb3gbrhg',
                    ],
                    [
                        'params' => 'license_signature',
                        'type' => 'String',
                        'opt_or_req' => 'Required',
                        'description' => 'The random hash of the license',
                        'values' => 'uyyf3ytfgvq23ehq3y3tq362t763e2873y81723',
                    ]
                ]),
                'is_active' => 1,
            ],
            [
                'name' => 'Download and Extract Version Files',
                'category_id' => 1,
                'endpoint' => '/api/downloadFile',
                'method' => 'POST',
                'description' => 'This API is used to download and extract archive with files of a specified version.',
                'parameters' => json_encode([
                    [
                        'params' => 'product_id',
                        'type' => 'Integer',
                        'opt_or_req' => 'Required',
                        'description' => 'The key of the product Id',
                        'values' => '8',
                    ],
                    [
                        'params' => 'client_email',
                        'type' => 'String',
                        'opt_or_req' => 'Optional',
                        'description' => 'The email of the client',
                        'values' => '',
                    ],
                    [
                        'params' => 'license_code',
                        'type' => 'String',
                        'opt_or_req' => 'Required',
                        'description' => 'The code of the license',
                        'values' => 'VWNKDSNCJKCNSU89',
                    ],
                    [
                        'params' => 'root_url',
                        'type' => 'String',
                        'opt_or_req' => 'Required',
                        'description' => 'The domain URL of the product',
                        'values' => 'https://demo.localhost/',
                    ],
                    [
                        'params' => 'installation_hash',
                        'type' => 'String',
                        'opt_or_req' => 'Required',
                        'description' => 'The random hash of the installation',
                        'values' => '75hgvdhgwvkjgweyu2t675672f3kjgb3gbrhg',
                    ],
                    [
                        'params' => 'license_signature',
                        'type' => 'String',
                        'opt_or_req' => 'Required',
                        'description' => 'The random hash of the license',
                        'values' => 'uyyf3ytfgvq23ehq3y3tq362t763e2873y81723',
                    ]
                ]),
                'is_active' => 1,
            ],
            [
                'name' => 'Register',
                'category_id' => 2,
                'endpoint' => '/register',
                'method' => 'POST',
                'description' => 'Registers a new user.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Login',
                'category_id' => 2,
                'endpoint' => '/login',
                'method' => 'POST',
                'description' => 'Authenticates a user and returns an access token.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Forgot Password',
                'category_id' => 2,
                'endpoint' => '/forgot',
                'method' => 'POST',
                'description' => 'Initiates a password reset process by sending a reset link to the user’s email.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Reset Password',
                'category_id' => 2,
                'endpoint' => '/reset',
                'method' => 'POST',
                'description' => 'Resets the user’s password using the token sent to their email.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Save Debug Value',
                'category_id' => 2,
                'endpoint' => '/save-debug-value',
                'method' => 'POST',
                'description' => 'Saves the debug settings value.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Save Token For Debugger',
                'category_id' => 2,
                'endpoint' => '/saveTokenForDebugger',
                'method' => 'POST',
                'description' => 'Saves the token for the debugger.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Get reCAPTCHA Status',
                'category_id' => 2,
                'endpoint' => '/recaptchaStatus',
                'method' => 'GET',
                'description' => 'Retrieves the current status of reCAPTCHA.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Verify Recovery Code',
                'category_id' => 2,
                'endpoint' => '/verify-recovery-code',
                'method' => 'POST',
                'description' => 'Verifies the recovery code provided by the user.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Verify 2FA',
                'category_id' => 2,
                'endpoint' => '/verify2fa',
                'method' => 'POST',
                'description' => 'Verifies the 2FA code provided by the user.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Enable Two-Factor Authentication',
                'category_id' => 3,
                'endpoint' => '/2fa/enable',
                'method' => 'POST',
                'description' => 'Enables two-factor authentication for the user.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Generate 2FA Recovery Code',
                'category_id' => 3,
                'endpoint' => '/2fa-recovery-code',
                'method' => 'POST',
                'description' => 'Generates a new recovery code for two-factor authentication.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Setup Validate Token',
                'category_id' => 3,
                'endpoint' => '/2fa/setupValidate',
                'method' => 'POST',
                'description' => 'Validates the setup token for two-factor authentication.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Disable Two-Factor Authentication',
                'category_id' => 3,
                'endpoint' => '/2fa/disable',
                'method' => 'POST',
                'description' => 'Disables two-factor authentication for the user.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Show Verify Password Popup',
                'category_id' => 3,
                'endpoint' => '/show/verify-password',
                'method' => 'GET',
                'description' => 'Displays a popup for verifying the user’s password.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Download 2FA Recovery Codes',
                'category_id' => 3,
                'endpoint' => '/2fa/downloadRecoveryCode',
                'method' => 'GET',
                'description' => 'Downloads the recovery codes for two-factor authentication.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Verify Password',
                'category_id' => 3,
                'endpoint' => '/verify/password',
                'method' => 'POST',
                'description' => 'Verifies the user’s password for two-factor authentication.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Get Profile Info',
                'category_id' => 4,
                'endpoint' => '/profile/info',
                'method' => 'GET',
                'description' => 'Retrieves the user’s profile information.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Update Profile',
                'category_id' => 4,
                'endpoint' => '/profile',
                'method' => 'PATCH',
                'description' => 'Updates the user’s profile information.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Update Password',
                'category_id' => 4,
                'endpoint' => '/password',
                'method' => 'PATCH',
                'description' => 'Updates the user’s password.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Get Country Code',
                'category_id' => 4,
                'endpoint' => '/countryCode',
                'method' => 'GET',
                'description' => 'Retrieves the country code for the user.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Add Product',
                'category_id' => 10,
                'endpoint' => '/products/add',
                'method' => 'POST',
                'description' => 'Adds a new product.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'View Products',
                'category_id' => 10,
                'endpoint' => '/viewproducts',
                'method' => 'GET',
                'description' => 'Displays the list of products.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Delete Product',
                'category_id' => 10,
                'endpoint' => '/products/delete',
                'method' => 'POST',
                'description' => 'Deletes a product.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Edit Product',
                'category_id' => 10,
                'endpoint' => '/products/edit',
                'method' => 'POST',
                'description' => 'Updates product details.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Get Product for Editing',
                'category_id' => 10,
                'endpoint' => '/product/{product_id}',
                'method' => 'GET',
                'description' => 'Fetches product details for editing.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'View Product Details',
                'category_id' => 10,
                'endpoint' => '/productView/{product_id}',
                'method' => 'GET',
                'description' => 'Displays detailed information about a product.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'View Product Installations',
                'category_id' => 10,
                'endpoint' => '/productInstallations/{product_id}',
                'method' => 'GET',
                'description' => 'Displays the installations associated with a product.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'View Product Licenses',
                'category_id' => 10,
                'endpoint' => '/productLicenses/{product_id}',
                'method' => 'GET',
                'description' => 'Displays the licenses associated with a product.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'View Product Versions',
                'category_id' => 10,
                'endpoint' => '/productVersions/{product_id}',
                'method' => 'GET',
                'description' => 'Displays the versions associated with a product.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'View Versions',
                'category_id' => 16,
                'endpoint' => '/viewVersions',
                'method' => 'GET',
                'description' => 'Displays the list of versions.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'View Version Info',
                'category_id' => 16,
                'endpoint' => '/versionView/{version_id}',
                'method' => 'GET',
                'description' => 'Displays detailed information about a specific version.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'View Version Callbacks',
                'category_id' => 16,
                'endpoint' => '/versionCallbacks/{version_id}',
                'method' => 'GET',
                'description' => 'Displays the callbacks associated with a specific version.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Add Client',
                'category_id' => 11,
                'endpoint' => '/clients/add',
                'method' => 'POST',
                'description' => 'Adds a new client.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'View Client',
                'category_id' => 11,
                'endpoint' => '/viewClients/{client_id}',
                'method' => 'GET',
                'description' => 'Displays the details of a specific client.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Delete Client',
                'category_id' => 11,
                'endpoint' => '/clients/delete',
                'method' => 'POST',
                'description' => 'Deletes a client.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Edit Client',
                'category_id' => 11,
                'endpoint' => '/clients/edit',
                'method' => 'POST',
                'description' => 'Updates client details.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Get Client for Editing',
                'category_id' => 11,
                'endpoint' => '/client/{client_id}',
                'method' => 'GET',
                'description' => 'Fetches client details for editing.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'View Client Info',
                'category_id' => 11,
                'endpoint' => '/clientView/{client_id}',
                'method' => 'GET',
                'description' => 'Displays detailed information about a client.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'View Client Installations',
                'category_id' => 11,
                'endpoint' => '/clientInstallations/{client_id}',
                'method' => 'GET',
                'description' => 'Displays the installations associated with a client.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'View Client Licenses',
                'category_id' => 11,
                'endpoint' => '/clientLicenses/{client_id}',
                'method' => 'GET',
                'description' => 'Displays the licenses associated with a client.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Add License',
                'category_id' => 12,
                'endpoint' => '/license/add',
                'method' => 'POST',
                'description' => 'Adds a new license.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'View Licenses',
                'category_id' => 12,
                'endpoint' => '/viewLicenses',
                'method' => 'GET',
                'description' => 'Displays the list of licenses.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Delete License',
                'category_id' => 12,
                'endpoint' => '/license/delete',
                'method' => 'POST',
                'description' => 'Deletes a license.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Edit License',
                'category_id' => 12,
                'endpoint' => '/license/edit',
                'method' => 'POST',
                'description' => 'Updates license details.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Get License for Editing',
                'category_id' => 12,
                'endpoint' => '/license/{license_id}',
                'method' => 'GET',
                'description' => 'Fetches license details for editing.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Deactivate License',
                'category_id' => 12,
                'endpoint' => '/license/deactivate',
                'method' => 'POST',
                'description' => 'Deactivates a license.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Update License Code',
                'category_id' => 12,
                'endpoint' => '/license/updateLicenseCode',
                'method' => 'POST',
                'description' => 'Updates the license code.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'View License Details',
                'category_id' => 12,
                'endpoint' => '/licenseView/{license_id}',
                'method' => 'GET',
                'description' => 'Displays detailed information about a license.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'View License Installations',
                'category_id' => 12,
                'endpoint' => '/licenseInstallation/{license_id}',
                'method' => 'GET',
                'description' => 'Displays the installations associated with a license.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'View License Callbacks',
                'category_id' => 12,
                'endpoint' => '/licenseCallbacks/{license_id}',
                'method' => 'GET',
                'description' => 'Displays the callbacks associated with a license.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Get License Columns',
                'category_id' => 12,
                'endpoint' => '/getLicenseColumn',
                'method' => 'GET',
                'description' => 'Retrieves the license columns.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Save License Columns',
                'category_id' => 12,
                'endpoint' => '/saveLicenseColumn',
                'method' => 'POST',
                'description' => 'Saves the license columns.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'View License Installation Logs',
                'category_id' => 12,
                'endpoint' => '/installationLogs/{id}',
                'method' => 'GET',
                'description' => 'Displays the installation logs associated with a license.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Delete Installations',
                'category_id' => 13,
                'endpoint' => '/installations/delete',
                'method' => 'POST',
                'description' => 'Deletes specific installations.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Edit Installation',
                'category_id' => 13,
                'endpoint' => '/installations/edit',
                'method' => 'POST',
                'description' => 'Updates installation details.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'View Installations',
                'category_id' => 13,
                'endpoint' => '/viewInstallations',
                'method' => 'GET',
                'description' => 'Displays the list of installations.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Add Installation',
                'category_id' => 13,
                'endpoint' => '/addInstallation',
                'method' => 'POST',
                'description' => 'Adds a new installation.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Get Installation for Editing',
                'category_id' => 13,
                'endpoint' => '/installation/{installation_id}',
                'method' => 'GET',
                'description' => 'Fetches installation details for editing.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Reissue Installation',
                'category_id' => 13,
                'endpoint' => '/installation/reissue',
                'method' => 'POST',
                'description' => 'Removes unwanted installations.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Update Installation License Code',
                'category_id' => 13,
                'endpoint' => '/installation/updateLicenseCode',
                'method' => 'POST',
                'description' => 'Updates the license code for an installation.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'View Installation Details',
                'category_id' => 13,
                'endpoint' => '/installationView/{installation_id}',
                'method' => 'GET',
                'description' => 'Displays detailed information about an installation.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'View Installation Callbacks',
                'category_id' => 13,
                'endpoint' => '/installationCallbacks/{installation_id}',
                'method' => 'GET',
                'description' => 'Displays the callbacks associated with an installation.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Add Banned Host',
                'category_id' => 14,
                'endpoint' => '/bannedHosts/add',
                'method' => 'POST',
                'description' => 'Adds a new banned host.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Delete Banned Host',
                'category_id' => 14,
                'endpoint' => '/bannedHosts/delete',
                'method' => 'POST',
                'description' => 'Deletes a banned host.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Edit Banned Host',
                'category_id' => 14,
                'endpoint' => '/bannedHosts/edit',
                'method' => 'POST',
                'description' => 'Updates details of a banned host.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'View Banned Hosts',
                'category_id' => 14,
                'endpoint' => '/viewBannedHost',
                'method' => 'GET',
                'description' => 'Displays the list of banned hosts.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'View Banned Host Details',
                'category_id' => 14,
                'endpoint' => '/viewBannedHost/{banned_host_id}',
                'method' => 'GET',
                'description' => 'Displays details of a specific banned host.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Update or Create Whitelist IP',
                'category_id' => 15,
                'endpoint' => '/whitelist/updateOrCreate',
                'method' => 'POST',
                'description' => 'Adds or updates a whitelist IP.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Edit Whitelist IP',
                'category_id' => 15,
                'endpoint' => '/whitelist-edit/{id}',
                'method' => 'GET',
                'description' => 'Fetches details for editing a whitelist IP.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Delete Whitelist IP',
                'category_id' => 15,
                'endpoint' => '/delete-whitelist-ip',
                'method' => 'POST',
                'description' => 'Deletes a whitelist IP.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'View Whitelist IPs',
                'category_id' => 15,
                'endpoint' => '/view-Whitelist',
                'method' => 'GET',
                'description' => 'Displays the list of whitelist IPs.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Create or Update Common Setting',
                'category_id' => 8,
                'endpoint' => '/common-setting',
                'method' => 'POST',
                'description' => 'Creates or updates a common setting.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Get Common Setting',
                'category_id' => 8,
                'endpoint' => '/common-setting/get',
                'method' => 'GET',
                'description' => 'Retrieves the current common setting.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Reset Common Setting',
                'category_id' => 8,
                'endpoint' => '/common-setting/reset',
                'method' => 'POST',
                'description' => 'Clears the common setting.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Get Timezones',
                'category_id' => 8,
                'endpoint' => '/timezones',
                'method' => 'GET',
                'description' => 'Retrieves a dropdown list of timezones.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Get Date Formats',
                'category_id' => 8,
                'endpoint' => '/date-formats',
                'method' => 'GET',
                'description' => 'Retrieves a dropdown list of date formats.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Get Time Formats',
                'category_id' => 8,
                'endpoint' => '/time-formats',
                'method' => 'GET',
                'description' => 'Retrieves a dropdown list of time formats.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Get Cleanup Settings',
                'category_id' => 9,
                'endpoint' => '/cleanupSettings',
                'method' => 'GET',
                'description' => 'Retrieves dropdown options for cleanup settings.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Get Clean Settings',
                'category_id' => 9,
                'endpoint' => '/cleanSettings',
                'method' => 'GET',
                'description' => 'Retrieves options for clean settings.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Save Interval Settings',
                'category_id' => 9,
                'endpoint' => '/saveintervalSettings',
                'method' => 'POST',
                'description' => 'Saves the interval settings.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Save License Expire Range',
                'category_id' => 9,
                'endpoint' => '/saveLicenseExpireRange',
                'method' => 'POST',
                'description' => 'Saves the license expiration range.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Get Updates Expirings',
                'category_id' => 9,
                'endpoint' => '/getUpdatesExpirings',
                'method' => 'GET',
                'description' => 'Retrieves information about expiring updates.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Save Support Expire Range',
                'category_id' => 9,
                'endpoint' => '/saveSupportExpireRange',
                'method' => 'POST',
                'description' => 'Saves the support expiration range.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Get Support Expirings',
                'category_id' => 9,
                'endpoint' => '/getSupportExpirings',
                'method' => 'GET',
                'description' => 'Retrieves information about expiring support.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Get Debugger',
                'category_id' => 9,
                'endpoint' => '/getDebugger',
                'method' => 'GET',
                'description' => 'Retrieves debugger settings.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Get Cron Time Commands',
                'category_id' => 9,
                'endpoint' => '/cronTimeCommands',
                'method' => 'GET',
                'description' => 'Retrieves commands for cron time settings.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Get Interval Time',
                'category_id' => 9,
                'endpoint' => '/intervalTime',
                'method' => 'GET',
                'description' => 'Retrieves interval time settings.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Verify PHP Path',
                'category_id' => 9,
                'endpoint' => '/verify-php-path',
                'method' => 'POST',
                'description' => 'Verifies the PHP executable path.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Handle Notification',
                'category_id' => 7,
                'endpoint' => '/notifications/{notification_id}',
                'method' => 'POST',
                'description' => 'Handles the specified notification.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Send Emails',
                'category_id' => 7,
                'endpoint' => '/emails',
                'method' => 'POST',
                'description' => 'Sends emails based on the request.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'View Notifications',
                'category_id' => 7,
                'endpoint' => '/viewNotifications',
                'method' => 'GET',
                'description' => 'Retrieves a list of notifications.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'View Emails',
                'category_id' => 7,
                'endpoint' => '/viewEmails',
                'method' => 'GET',
                'description' => 'Retrieves a list of emails.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Edit Profile',
                'category_id' => 4,
                'endpoint' => '/editprofile/{admin_id}',
                'method' => 'POST',
                'description' => 'Edits the profile of the specified admin.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Generate Config',
                'category_id' => 22,
                'endpoint' => '/config',
                'method' => 'POST',
                'description' => 'Generates configuration settings.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Get Exception Logs',
                'category_id' => 20,
                'endpoint' => '/logs/exception',
                'method' => 'GET',
                'description' => 'Retrieves the exception logs.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Search',
                'category_id' => 23,
                'endpoint' => '/search',
                'method' => 'POST',
                'description' => 'Performs a search based on the request.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Add New API Key',
                'category_id' => 17,
                'endpoint' => '/addnewapi',
                'method' => 'POST',
                'description' => 'Adds a new API key.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Edit API Key',
                'category_id' => 17,
                'endpoint' => '/editnewapi/{api_key_id}',
                'method' => 'POST',
                'description' => 'Updates an existing API key.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Delete API Key',
                'category_id' => 17,
                'endpoint' => '/deleteapi/{api_key_id}',
                'method' => 'POST',
                'description' => 'Deletes the specified API key.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'View API Key',
                'category_id' => 17,
                'endpoint' => '/viewApiKeys/{api_key_id}',
                'method' => 'GET',
                'description' => 'Retrieves details of the specified API key.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Delete Report',
                'category_id' => 21,
                'endpoint' => '/reports/delete',
                'method' => 'POST',
                'description' => 'Deletes a specified report.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'System Report',
                'category_id' => 21,
                'endpoint' => '/reportSystem',
                'method' => 'GET',
                'description' => 'Retrieves the system report array.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'License Report',
                'category_id' => 21,
                'endpoint' => '/reportLicense',
                'method' => 'GET',
                'description' => 'Retrieves the license report array.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Cracking Report',
                'category_id' => 21,
                'endpoint' => '/reportCracking',
                'method' => 'GET',
                'description' => 'Retrieves the cracking report array.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Update Report',
                'category_id' => 21,
                'endpoint' => '/reportUpdate',
                'method' => 'GET',
                'description' => 'Retrieves the update report array.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Update and Add Product',
                'category_id' => 10,
                'endpoint' => '/products/UpdateAdd',
                'method' => 'POST',
                'description' => 'Updates or adds a new product.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Update and Delete Product',
                'category_id' => 10,
                'endpoint' => '/products/UpdateDelete',
                'method' => 'POST',
                'description' => 'Deletes or updates a product.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Update Product',
                'category_id' => 10,
                'endpoint' => '/products/UpdateEdit',
                'method' => 'POST',
                'description' => 'Updates an existing product.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Get Products',
                'category_id' => 10,
                'endpoint' => '/afuProducts',
                'method' => 'GET',
                'description' => 'Retrieves a list of products.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Add Version',
                'category_id' => 16,
                'endpoint' => '/versions/add',
                'method' => 'POST',
                'description' => 'Adds a new version.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Edit Version',
                'category_id' => 16,
                'endpoint' => '/versions/edit',
                'method' => 'POST',
                'description' => 'Updates an existing version.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Delete Version',
                'category_id' => 16,
                'endpoint' => '/versions/delete',
                'method' => 'POST',
                'description' => 'Deletes a specified version.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Set Directory Path',
                'category_id' => 18,
                'endpoint' => '/setPath',
                'method' => 'POST',
                'description' => 'Sets the directory path.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Update Notification Fields',
                'category_id' => 7,
                'endpoint' => '/updateNotifications/{notification_id}',
                'method' => 'POST',
                'description' => 'Updates the fields of a specific notification.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Show Update Notifications',
                'category_id' => 7,
                'endpoint' => '/showUpdateNotifications',
                'method' => 'GET',
                'description' => 'Retrieves a list of updated notifications.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Show License Callbacks',
                'category_id' => 19,
                'endpoint' => '/showLicenseCallbacks',
                'method' => 'GET',
                'description' => 'Retrieves the list of license callbacks.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Show Update Callbacks',
                'category_id' => 19,
                'endpoint' => '/showUpdateCallbacks',
                'method' => 'GET',
                'description' => 'Retrieves the list of update callbacks.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Delete Callback',
                'category_id' => 19,
                'endpoint' => '/callbackdelete',
                'method' => 'POST',
                'description' => 'Deletes a specific callback.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Edit Updated Installation',
                'category_id' => 13,
                'endpoint' => '/updatedInstallation/edit',
                'method' => 'POST',
                'description' => 'Edits an updated installation.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Show Updated Installations',
                'category_id' => 13,
                'endpoint' => '/showUpdateInstall',
                'method' => 'GET',
                'description' => 'Retrieves a list of updated installations.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Update Installation Logs',
                'category_id' => 12,
                'endpoint' => '/updateInstallationLogs',
                'method' => 'POST',
                'description' => 'Updates the installation logs.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Get Installation Logs',
                'category_id' => 12,
                'endpoint' => '/getInstallationLogs',
                'method' => 'POST',
                'description' => 'Retrieves the installation logs.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Get Profile Info',
                'category_id' => 4,
                'endpoint' => '/profile/info',
                'method' => 'GET',
                'description' => 'Retrieves information about the user profile.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Update Profile',
                'category_id' => 4,
                'endpoint' => '/profile',
                'method' => 'PATCH',
                'description' => 'Updates the user profile information.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Update Password',
                'category_id' => 4,
                'endpoint' => '/password',
                'method' => 'PATCH',
                'description' => 'Updates the user password.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'Get Country Code',
                'category_id' => 4,
                'endpoint' => '/countryCode',
                'method' => 'GET',
                'description' => 'Retrieves the country code.',
                'parameters' => null,
                'is_active' => 1,
            ],
            [
                'name' => 'View API Keys',
                'category_id' => 17,
                'endpoint' => '/admin/viewApiKeys',
                'method' => 'GET',
                'description' => 'Retrieves a list of API keys.',
                'parameters' => null,
                'is_active' => 1,
            ],
        ];

        ApiInfo::insert($api);
    }
    public function category()
    {
        $categories = [
            ['category_id' => 1, 'category' => 'A Product to License Manager', 'description' => 'APIs for handling license management, verification, and related processes.'],
            ['category_id' => 2, 'category' => 'User Login and Password Reset', 'description' => 'APIs for user authentication, including login, password recovery, and reset.'],
            ['category_id' => 3, 'category' => 'Two-Factor Authentication', 'description' => 'APIs for managing two-factor authentication settings and processes.'],
            ['category_id' => 4, 'category' => 'Profile', 'description' => 'APIs for managing user profiles, including updates and viewing profile information.'],
            ['category_id' => 5, 'category' => 'Security Settings', 'description' => 'APIs for managing security configurations and settings.'],
            ['category_id' => 6, 'category' => 'Email Settings', 'description' => 'APIs for configuring and managing email settings and notifications.'],
            ['category_id' => 7, 'category' => 'Notification', 'description' => 'APIs for managing notifications and related settings.'],
            ['category_id' => 8, 'category' => 'General Settings', 'description' => 'APIs for managing general application settings and configurations.'],
            ['category_id' => 9, 'category' => 'Cleanup Settings', 'description' => 'APIs for managing application cleanup and maintenance tasks.'],
            ['category_id' => 10, 'category' => 'Products', 'description' => 'APIs for managing products, including creation, updates, and deletion.'],
            ['category_id' => 11, 'category' => 'Clients', 'description' => 'APIs for managing client information and operations.'],
            ['category_id' => 12, 'category' => 'Licenses', 'description' => 'APIs for managing licenses, including issuance, updates, and verification.'],
            ['category_id' => 13, 'category' => 'Installations', 'description' => 'APIs for managing installation processes and related data.'],
            ['category_id' => 14, 'category' => 'Banned Hosts', 'description' => 'APIs for managing and monitoring banned hosts.'],
            ['category_id' => 15, 'category' => 'Whitelist', 'description' => 'APIs for managing IP whitelist settings.'],
            ['category_id' => 16, 'category' => 'Versions', 'description' => 'APIs for retrieving and managing version information.'],
            ['category_id' => 17, 'category' => 'API Keys', 'description' => 'APIs for creating, updating, and deleting API keys.'],
            ['category_id' => 18, 'category' => 'Directory', 'description' => 'APIs for setting and managing directory paths for archives and queries.'],
            ['category_id' => 19, 'category' => 'Callback', 'description' => 'APIs for handling and managing callbacks related to updates and licenses.'],
            ['category_id' => 20, 'category' => 'Exception Logs', 'description' => 'APIs for accessing and managing exception logs.'],
            ['category_id' => 21, 'category' => 'Report', 'description' => 'APIs for generating and managing reports on licenses, updates, and other activities.'],
            ['category_id' => 22, 'category' => 'Config Generator', 'description' => 'APIs for generating config.'],
            ['category_id' => 23, 'category' => 'Search', 'description' => 'Performs a search based on the request.'],
        ];

        foreach ($categories as $category) {
           ApiCategories::updateOrInsert(
                ['category_id' => $category['category_id']],
                ['category' => $category['category'], 'description' => $category['description']]
            );
        }
    }
}
